### PR TITLE
Added: Add an optional priority field to the journals 

### LINKED ISSUE #270: Reordering entries
I would like to have special keys to reorder the entries, for example:

- Ctrl + K -> move the entry to one entry above
- Ctrl + J -> same, but one entry below

My reasoning is that I want to sort my notes by their importance/priority. 

Related: #264

### PR DESCRIPTION
**Pull request by AmmarAbouZor**
This PR closes #270

This is still work in progress

This PR should provide:
- [x] Introduce an optional priority field to the journals on both backends  (json, sqlite) with the needed migrations & conversions
- [x] Adjust the unit tests to test the functionalities with the newly added priority field
- [x] Adjust The App UI to let the users set and change the priority in the journal popup
- [x] Show the priority in the journals list if available
- [x] Integrate the priorities in the filter + expand the unit test to cover it as well

### CODE REVIEW

**Comment by orhun** [comment]
Hey, just tried this. Is there way to set a priority for the existing entries?

**Comment by AmmarAbouZor** [comment]
@orhun I can provide a sub cli-command to assign a priority to all the items that don't have any. You can create an issue for that and I'll provide a PR for it before I start with the sorting implementation.

For more complex situations you can have more control on the entries by applying SQL scripts on the journals file directly since it's a sqlite database, which can be exterminated and manipulated easily with any SQLite tool

**Comment by AmmarAbouZor** [comment]
@orhun I've created the Issue #295 for the cli command and we'll starting working on it

**Comment by AmmarAbouZor** [comment]
@orhun Sure if you want to assign the a priority manually you can do that from within the app by choosing edit journal command with shortcut `e`.
For assigning all the journals at once, I've add a new sub-command #296

**Comment by orhun** [comment]
Sorry for the late reply :/ thanks for creating the issue!

Just tried it out and works great! Are you also going to add an option to sort by priority? 🐻

**Comment by AmmarAbouZor** [comment]
@orhun That's gonna be my next step to implement sorting mechanism using date, priority, and name #264 . Hopefully I'll get to it in the next few days :+1:

**Pull request merged**
