### PR TITLE
Add NetBSD

### PR DESCRIPTION
**Pull request by 0323pin**
I've packaged `tui-journal` for NetBSD and just merged the package into pkgsrc main branch.

For your reference, here's the commit log, http://mail-index.netbsd.org/pkgsrc-changes/2023/05/14/msg274757.html

Regards

### CODE REVIEW

**Comment by ammarabouzor** [comment]
Thanks for adding `tui-journal` to your OS packages

Regards

**Comment by 0323pin** [comment]
Thanks!
Are you planning to add the project to crates.io or, shall I add it to my RSS-feeds to monitor new releases?

**Comment by ammarabouzor** [comment]
I've prepared the repo to be published in on crates.io. There is still a dependencies miss match between ratatui and tui-textarea crates which failed the publish process. 
It should be fixed in the next day though then I'll publish the repo on crates.io

**Comment by 0323pin** [comment]
Thanks!
I'll try to keep track of releases and the package up-to-date. Hopefully, the issue with `ratatui`/`tui-textarea` is solved.

**Comment by ammarabouzor** [comment]
It's online on [crates.io](https://crates.io/crates/tui-journal), but I had to go back to tui-rs.

The implementation in tui-textarea is actually done. But the version on crates.io is still an old one. I tried to use the link to his github repo in my dependencies but crates.io doesn't allow dependencies from GitHub. I opened an [Issue](https://github.com/rhysd/tui-textarea/issues/18) there and hopefully it will be issued soon then I can reactivate the migration to ratatui

**Pull request merged**
